"use client";

import { Fragment, type CSSProperties } from "react";
import { AnimShell, useStepper } from "./anim";

/* ──────────────────────────────────────────────
   AlgoTrace — the "hold the data in your head"
   stage. Every step draws ALL the state the
   algorithm is carrying (the array with named
   pointers, the hash map, the stack, the heap as
   a tree AND an array, the DP grid, intervals on
   a number line, bits in rows) next to the real
   Go code with the current line lit.

   Frames are GENERATED by running the real Go
   algorithm with a tracer (scripts/algotrace),
   never hand-typed, so what you see is what the
   code actually did.
   ────────────────────────────────────────────── */

type Cell = string | number;
export type Mark = "hot" | "good" | "bad" | "dim" | "win";

export type TraceView =
  | { k: "array"; label?: string; cells: Cell[]; ptrs?: Record<string, number>; marks?: Record<number, Mark> }
  | { k: "stack" | "queue"; label?: string; items: Cell[]; hot?: "push" | "pop" }
  | { k: "map"; label?: string; entries: [Cell, Cell][]; hot?: Cell }
  | { k: "heap"; label?: string; cells: number[]; marks?: Record<number, Mark> }
  | { k: "graph"; label?: string; states: Record<string, string>; edges?: string[]; at?: string }
  | { k: "tree"; label?: string; nodes: { id: string; label: Cell; parent?: string; state?: string }[]; edgeLabels?: Record<string, string> }
  | { k: "grid"; label?: string; rows: Cell[]; cols: Cell[]; cells: Cell[][]; hot?: [number, number]; deps?: [number, number][] }
  | { k: "intervals"; label?: string; lo: number; hi: number; rows: { a: number; b: number; label?: string; state?: Mark }[] }
  | { k: "bits"; label?: string; rows: { label: string; value: number; width: number; marks?: Record<number, Mark> }[] }
  | { k: "text"; label?: string; text: string };

export type TraceFrame = {
  note: string;
  beat?: "problem" | "solution" | "neutral";
  /** 1-based line of `code` that is executing at this step */
  line?: number;
  vars?: Record<string, Cell>;
  views: TraceView[];
};

export type TraceNode = { id: string; x: number; y: number };
/** [from, to] or [from, to, weight] */
export type TraceEdge = [string, string] | [string, string, number];

function Label({ text }: { text?: string }) {
  return text ? <div className="atr-label">{text}</div> : null;
}

function ArrayView({ v }: { v: Extract<TraceView, { k: "array" }> }) {
  const n = v.cells.length;
  const ptrs = Object.entries(v.ptrs ?? {});
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <div className="atr-arr" style={{ "--n": n } as CSSProperties}>
        {v.cells.map((c, i) => (
          <span key={i} className={`atr-cell ${v.marks?.[i] ? `m-${v.marks[i]}` : ""}`}>
            <i>{i}</i>
            {String(c)}
          </span>
        ))}
      </div>
      {ptrs.length > 0 && (
        <div className="atr-ptrs" style={{ "--n": n } as CSSProperties}>
          {ptrs.map(([name, at]) => {
            const stack = ptrs.filter(([, a]) => a === at).findIndex(([nm]) => nm === name);
            return (
              <span
                key={name}
                className="atr-ptr"
                style={{ "--at": at, "--st": stack } as CSSProperties}
              >
                <b>▲</b>
                {name}
              </span>
            );
          })}
        </div>
      )}
    </div>
  );
}

function StackQueueView({ v }: { v: Extract<TraceView, { k: "stack" | "queue" }> }) {
  const isStack = v.k === "stack";
  const items = v.items ?? [];
  return (
    <div className="atr-block">
      <Label text={v.label ?? (isStack ? "stack (top on the right)" : "queue (front on the left)")} />
      <div className="atr-row">
        <span className="atr-end">{isStack ? "bottom" : "front"}</span>
        {items.length === 0 && <span className="atr-empty">empty</span>}
        {items.map((c, i) => {
          const last = i === items.length - 1;
          const hot = isStack ? last : last || i === 0;
          return (
            <span key={i} className={`atr-box ${hot && v.hot ? "m-hot" : ""}`}>
              {String(c)}
            </span>
          );
        })}
        <span className="atr-end">{isStack ? "top" : "back"}</span>
      </div>
    </div>
  );
}

function MapView({ v }: { v: Extract<TraceView, { k: "map" }> }) {
  return (
    <div className="atr-block">
      <Label text={v.label ?? "map"} />
      <div className="atr-row atr-wrap">
        {(v.entries ?? []).length === 0 && <span className="atr-empty">empty</span>}
        {(v.entries ?? []).map(([k, val]) => (
          <span key={String(k)} className={`atr-kv ${v.hot !== undefined && String(v.hot) === String(k) ? "m-hot" : ""}`}>
            <em>{String(k)}</em>
            <b>→</b>
            {String(val)}
          </span>
        ))}
      </div>
    </div>
  );
}

function HeapView({ v }: { v: Extract<TraceView, { k: "heap" }> }) {
  const n = v.cells.length;
  const depth = n === 0 ? 0 : Math.floor(Math.log2(n)) + 1;
  const W = 300;
  const H = Math.max(60, depth * 52 + 16);
  const pos = (i: number) => {
    const d = Math.floor(Math.log2(i + 1));
    const first = 2 ** d - 1;
    const slot = i - first;
    const per = 2 ** d;
    return { x: ((slot + 0.5) / per) * W, y: 22 + d * 50 };
  };
  return (
    <div className="atr-block">
      <Label text={v.label ?? "heap: tree view + array view (same data)"} />
      <svg className="atr-svg" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="heap as a tree">
        {v.cells.map((_, i) => {
          if (i === 0) return null;
          const a = pos(Math.floor((i - 1) / 2));
          const b = pos(i);
          return <line key={`e${i}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="atr-edge" />;
        })}
        {v.cells.map((c, i) => {
          const p = pos(i);
          return (
            <g key={i} className={`atr-node ${v.marks?.[i] ? `m-${v.marks[i]}` : ""}`}>
              <circle cx={p.x} cy={p.y} r={16} />
              <text x={p.x} y={p.y + 4} textAnchor="middle">
                {c}
              </text>
              <text x={p.x + 17} y={p.y - 12} className="atr-nidx">
                {i}
              </text>
            </g>
          );
        })}
      </svg>
      <div className="atr-arr" style={{ "--n": Math.max(n, 1) } as CSSProperties}>
        {v.cells.map((c, i) => (
          <span key={i} className={`atr-cell ${v.marks?.[i] ? `m-${v.marks[i]}` : ""}`}>
            <i>{i}</i>
            {String(c)}
          </span>
        ))}
      </div>
      {n > 1 && <div className="atr-hint">parent of i = (i−1)/2 · children = 2i+1, 2i+2</div>}
    </div>
  );
}

function GraphView({
  v,
  nodes,
  edges,
}: {
  v: Extract<TraceView, { k: "graph" }>;
  nodes: TraceNode[];
  edges: TraceEdge[];
}) {
  const pos = Object.fromEntries(nodes.map((n) => [n.id, n]));
  const lit = new Set(v.edges ?? []);
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <svg className="atr-svg" viewBox="0 0 300 170" role="img" aria-label="graph">
        {edges.map(([a, b, w]) => {
          const on = lit.has(`${a}-${b}`) || lit.has(`${b}-${a}`);
          const A = pos[a];
          const B = pos[b];
          return (
            <g key={`${a}${b}`}>
              <line x1={A.x} y1={A.y} x2={B.x} y2={B.y} className={`atr-edge ${on ? "on" : ""}`} />
              {w !== undefined && (
                <text x={(A.x + B.x) / 2} y={(A.y + B.y) / 2 - 4} className="atr-w" textAnchor="middle">
                  {w}
                </text>
              )}
            </g>
          );
        })}
        {nodes.map((n) => (
          <g key={n.id} className={`atr-node gs-${v.states[n.id] ?? "idle"} ${v.at === n.id ? "at" : ""}`}>
            <circle cx={n.x} cy={n.y} r={16} />
            <text x={n.x} y={n.y + 4} textAnchor="middle">
              {n.id}
            </text>
          </g>
        ))}
      </svg>
    </div>
  );
}

function TreeView({ v }: { v: Extract<TraceView, { k: "tree" }> }) {
  const nodes = v.nodes ?? [];
  const kids: Record<string, string[]> = {};
  const byId: Record<string, (typeof nodes)[number]> = {};
  const roots: string[] = [];
  nodes.forEach((n) => {
    byId[n.id] = n;
    if (n.parent && nodes.some((m) => m.id === n.parent)) (kids[n.parent] ||= []).push(n.id);
    else roots.push(n.id);
  });
  const pos: Record<string, { x: number; y: number }> = {};
  let leaf = 0;
  let maxD = 0;
  const walk = (id: string, d: number): number => {
    maxD = Math.max(maxD, d);
    const ch = kids[id] ?? [];
    const x = ch.length === 0 ? leaf++ : ch.map((c) => walk(c, d + 1)).reduce((a, b) => a + b, 0) / ch.length;
    pos[id] = { x, y: d };
    return x;
  };
  roots.forEach((r) => walk(r, 0));
  const GX = 44;
  const W = Math.max(leaf, 1) * GX;
  const H = (maxD + 1) * 48 + 12;
  const px = (id: string) => pos[id].x * GX + GX / 2;
  const py = (id: string) => pos[id].y * 48 + 22;
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <div className="atr-scroll">
        <svg className="atr-svg" style={{ width: Math.max(W, 120), maxWidth: "none" }} viewBox={`0 0 ${Math.max(W, 120)} ${H}`} role="img" aria-label="tree">
          {nodes.map((n) =>
            n.parent && pos[n.parent] ? (
              <g key={`e${n.id}`}>
                <line x1={px(n.parent)} y1={py(n.parent)} x2={px(n.id)} y2={py(n.id)} className={`atr-edge ${n.state && n.state !== "idle" ? "on" : ""}`} />
                {v.edgeLabels?.[n.id] && (
                  <text x={(px(n.parent) + px(n.id)) / 2 + 6} y={(py(n.parent) + py(n.id)) / 2} className="atr-w">
                    {v.edgeLabels[n.id]}
                  </text>
                )}
              </g>
            ) : null
          )}
          {nodes.map((n) => (
            <g key={n.id} className={`atr-node ts-${n.state ?? "idle"}`}>
              <circle cx={px(n.id)} cy={py(n.id)} r={15} />
              <text x={px(n.id)} y={py(n.id) + 4} textAnchor="middle">
                {String(n.label)}
              </text>
            </g>
          ))}
        </svg>
      </div>
    </div>
  );
}

function GridView({ v }: { v: Extract<TraceView, { k: "grid" }> }) {
  const isDep = (r: number, c: number) => v.deps?.some(([a, b]) => a === r && b === c);
  const isHot = (r: number, c: number) => v.hot && v.hot[0] === r && v.hot[1] === c;
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <div className="atr-grid" style={{ "--c": v.cols.length + 1 } as CSSProperties}>
        <span className="atr-gh" />
        {v.cols.map((c, i) => (
          <span key={i} className="atr-gh">
            {String(c)}
          </span>
        ))}
        {v.cells.map((row, r) => (
          <Fragment key={r}>
            <span className="atr-gh">{String(v.rows[r])}</span>
            {row.map((c, cc) => (
              <span key={cc} className={`atr-gc ${isHot(r, cc) ? "m-hot" : isDep(r, cc) ? "m-win" : ""} ${c === "" ? "blank" : ""}`}>
                {String(c)}
              </span>
            ))}
          </Fragment>
        ))}
      </div>
    </div>
  );
}

function IntervalsView({ v }: { v: Extract<TraceView, { k: "intervals" }> }) {
  const span = Math.max(1, v.hi - v.lo);
  const ticks: number[] = [];
  for (let t = v.lo; t <= v.hi; t++) ticks.push(t);
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <div className="atr-int">
        <div className="atr-ticks">
          {ticks.map((t) => (
            <span key={t} style={{ left: `${((t - v.lo) / span) * 100}%` }}>
              {t}
            </span>
          ))}
        </div>
        {v.rows.map((r, i) => (
          <div key={i} className="atr-int-row">
            <span
              className={`atr-bar ${r.state ? `m-${r.state}` : ""}`}
              style={{ left: `${((r.a - v.lo) / span) * 100}%`, width: `${((r.b - r.a) / span) * 100}%` }}
            >
              {r.label ?? `[${r.a},${r.b}]`}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function BitsView({ v }: { v: Extract<TraceView, { k: "bits" }> }) {
  return (
    <div className="atr-block">
      <Label text={v.label} />
      <div className="atr-bits">
        {v.rows.map((r, i) => (
          <div key={i} className="atr-bitrow">
            <span className="atr-bl">{r.label}</span>
            <span className="atr-bcells">
              {Array.from({ length: r.width }, (_, j) => {
                const idx = r.width - 1 - j;
                const bit = (r.value >> idx) & 1;
                return (
                  <span key={j} className={`atr-bit b${bit} ${r.marks?.[idx] ? `m-${r.marks[idx]}` : ""}`}>
                    {bit}
                  </span>
                );
              })}
            </span>
            <span className="atr-bv">= {r.value}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

export function AlgoTrace({
  title,
  code,
  frames,
  nodes,
  edges,
  caption,
}: {
  title: string;
  /** the real Go source shown beside the state; frames point at its lines */
  code?: string;
  frames: TraceFrame[];
  /** graph views only: fixed node positions (x 0..300, y 0..170) and edges */
  nodes?: TraceNode[];
  edges?: TraceEdge[];
  caption?: string;
}) {
  const st = useStepper(frames.length, 1800);
  const f = frames[st.cur] ?? frames[0];
  const lines = code ? code.replace(/\n$/, "").split("\n") : null;
  const vars = Object.entries(f.vars ?? {});
  return (
    <AnimShell
      title={title}
      kicker="trace"
      note={f.note}
      beat={f.beat ?? "neutral"}
      cur={st.cur}
      total={frames.length}
      playing={st.playing}
      speed={st.speed}
      onSpeed={st.cycleSpeed}
      onReset={st.reset}
      onStep={st.step}
      onToggle={st.toggle}
      onGo={st.go}
      caption={caption}
    >
      <div className={`atr ${lines ? "has-code" : ""}`}>
        {lines && (
          <div className="atr-code" role="region" aria-label="the Go code being traced">
            {lines.map((ln, i) => (
              <span key={i} className={`atr-ln ${f.line === i + 1 ? "on" : ""}`}>
                <i>{i + 1}</i>
                {ln || " "}
              </span>
            ))}
          </div>
        )}
        <div className="atr-state">
          {vars.length > 0 && (
            <div className="atr-vars">
              {vars.map(([k, val]) => (
                <span key={k} className="atr-var">
                  <em>{k}</em> = {String(val)}
                </span>
              ))}
            </div>
          )}
          {f.views.map((v, i) => {
            switch (v.k) {
              case "array":
                return <ArrayView key={i} v={v} />;
              case "stack":
              case "queue":
                return <StackQueueView key={i} v={v} />;
              case "map":
                return <MapView key={i} v={v} />;
              case "heap":
                return <HeapView key={i} v={v} />;
              case "graph":
                return <GraphView key={i} v={v} nodes={nodes ?? []} edges={edges ?? []} />;
              case "grid":
                return <GridView key={i} v={v} />;
              case "tree":
                return <TreeView key={i} v={v} />;
              case "intervals":
                return <IntervalsView key={i} v={v} />;
              case "bits":
                return <BitsView key={i} v={v} />;
              case "text":
                return (
                  <div key={i} className="atr-block">
                    <Label text={v.label} />
                    <div className="atr-text">{v.text}</div>
                  </div>
                );
            }
          })}
        </div>
      </div>
    </AnimShell>
  );
}
