"use client";

import {
  createElement,
  Fragment,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { slug as ghSlug } from "github-slugger";
import {
  Gopher,
  inferRole,
  type GopherPose,
  type GopherRole,
  type GopherState,
} from "./Gopher";
import { recordQuickCheck, recordLab } from "@/lib/gamification";
import { playSuccess, playBuzzer, playFlag, playClick } from "@/lib/sound";
import { triggerConfetti } from "@/lib/confetti";
import { highlightGo } from "@/lib/highlight";
import { formatGo } from "@/lib/gofmt";

/* ──────────────────────────────────────────────
   Interactive (client) course components.
   Animations are CSS/JS only — no animation libs,
   honoring the prompt's "no deps beyond React".
   Motion principle: things TRAVEL (tokens between
   lanes, gophers between states) rather than just
   recolouring in place. prefers-reduced-motion
   collapses all of it to instant state changes.
   ────────────────────────────────────────────── */

/** Numbered sub-topic tab strip with a scroll-synced progress bar.
 *  `tabs` labels must match the H2 headings in the chapter; ids are
 *  generated by rehype-slug and matched here with github-slugger. */
export function ChapterTabs({ tabs }: { tabs: string[] }) {
  const [active, setActive] = useState(0);

  useEffect(() => {
    const ids = tabs.map((t) => ghSlug(t));
    const els = ids
      .map((id) => document.getElementById(id))
      .filter(Boolean) as HTMLElement[];
    if (!els.length) return;
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            const i = ids.indexOf((e.target as HTMLElement).id);
            if (i >= 0) setActive(i);
          }
        });
      },
      { rootMargin: "-45% 0px -50% 0px", threshold: 0 }
    );
    els.forEach((el) => obs.observe(el));
    return () => obs.disconnect();
  }, [tabs]);

  const go = (i: number) => {
    const el = document.getElementById(ghSlug(tabs[i]));
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
    setActive(i);
  };

  return (
    <nav className="tabs" aria-label="Chapter sections">
      <div className="tabs-row">
        {tabs.map((t, i) => (
          <button
            key={t}
            className={`tab ${i === active ? "tab-active" : ""} ${
              i < active ? "tab-done" : ""
            }`}
            onClick={() => go(i)}
          >
            <span className="tab-n">{i + 1}</span>
            <span className="tab-label">{t}</span>
          </button>
        ))}
      </div>
    </nav>
  );
}

type Lane = { id: string; label: string; role?: GopherRole };
type StepKind = "run" | "block" | "send" | "recv" | "spawn" | "done";
type Step = {
  lane: string;
  label: string;
  note?: string;
  kind?: StepKind;
  /** morph: while this step is current, its lane's gopher wears this costume
   *  (e.g. a "acquire lock" step turns the goroutine into a "guard") */
  role?: GopherRole;
};

const KIND_LABEL: Record<StepKind, string> = {
  run: "run",
  block: "block",
  send: "send ►",
  recv: "◄ recv",
  spawn: "go ✦",
  done: "done ✓",
};

/* compact glyphs for collapsed (already-played) steps */
const KIND_GLYPH: Record<StepKind, string> = {
  run: "▸",
  block: "⛔",
  send: "►",
  recv: "◄",
  spawn: "✦",
  done: "✓",
};

/* playback speed: cycles slow → fast. interval = base / speed. */
export const SPEEDS = [1, 0.5, 0.25, 2] as const;
export const speedLabel = (s: number) =>
  s === 0.5 ? "½×" : s === 0.25 ? "¼×" : `${s}×`;

/** Map a lane's CURRENT activity to a gopher pose + tint. A lane whose final
 *  step was `done` EXITS through the door (the goroutine returned); a lane
 *  whose current step is `spawn` ENTERS through it. */
function lanePose(
  now: Step | null,
  laneId: string,
  everRan: boolean,
  finished: boolean
): { pose: GopherPose; state: GopherState } {
  if (!now || now.lane !== laneId) {
    if (finished) return { pose: "exit", state: "done" };
    return { pose: everRan ? "idle" : "sleep", state: "idle" };
  }
  switch (now.kind ?? "run") {
    case "run":
      return { pose: "run", state: "active" };
    case "spawn":
      return { pose: "enter", state: "active" };
    case "send":
      return { pose: "carry", state: "active" };
    case "recv":
      return { pose: "carry", state: "ok" };
    case "block":
      return { pose: "blocked", state: "warn" };
    case "done":
      return { pose: "exit", state: "done" };
  }
}

type TokenFlight = {
  key: number;
  x0: number;
  y0: number;
  x1: number;
  y1: number;
};

/** Stepped "play" timeline. Lanes on the Y axis (e.g. goroutines / main),
 *  global ticks on the X axis. Each lane is fronted by a gopher actor whose
 *  pose tracks what that lane is doing RIGHT NOW; on a send, a token visibly
 *  flies from the send cell to the matching recv cell; a playhead glides
 *  across columns. Falls back to instant state changes under
 *  prefers-reduced-motion. */
export function ExecTimeline({
  title,
  lanes,
  steps,
  caption,
}: {
  title?: string;
  lanes: Lane[];
  steps: Step[];
  caption?: string;
}) {
  const [cur, setCur] = useState(-1);
  const [playing, setPlaying] = useState(false);
  const [speed, setSpeed] = useState(1);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  const matrixRef = useRef<HTMLDivElement | null>(null);
  const [flight, setFlight] = useState<TokenFlight | null>(null);
  const [flying, setFlying] = useState(false);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setCur((c) => {
        if (c >= steps.length - 1) {
          setPlaying(false);
          return c;
        }
        return c + 1;
      });
    }, 1050 / speed);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, steps.length, speed]);

  /* For each send step, the cell index of the recv it pairs with (the next
     recv after it). Precomputed once — drives the token flights. */
  const recvFor = useMemo(() => {
    const m = new Map<number, number>();
    steps.forEach((s, i) => {
      if ((s.kind ?? "run") !== "send") return;
      for (let j = i + 1; j < steps.length; j++) {
        if ((steps[j].kind ?? "run") === "recv") {
          m.set(i, j);
          break;
        }
      }
    });
    return m;
  }, [steps]);

  /* On entering a send step: launch a token from the send card to the
     receiving lane's track. Pure CSS transition does the travel. */
  useEffect(() => {
    const host = matrixRef.current;
    if (!host || cur < 0) {
      setFlight(null);
      return;
    }
    const j = recvFor.get(cur);
    if (j === undefined) {
      setFlight(null);
      return;
    }
    const from = host
      .querySelector<HTMLElement>(`[data-i="${cur}"]`)
      ?.getBoundingClientRect();
    const toTrack = host
      .querySelector<HTMLElement>(`[data-track="${steps[j].lane}"]`)
      ?.getBoundingClientRect();
    const base = host.getBoundingClientRect();
    if (!from || !toTrack) return;
    setFlying(false);
    setFlight({
      key: cur,
      x0: from.right - 10 - base.left,
      y0: from.top + from.height / 2 - base.top,
      x1: toTrack.left + 26 - base.left,
      y1: toTrack.top + toTrack.height / 2 - base.top,
    });
    const raf = requestAnimationFrame(() => requestAnimationFrame(() => setFlying(true)));
    return () => cancelAnimationFrame(raf);
  }, [cur, recvFor, steps]);

  const reset = () => {
    setPlaying(false);
    setCur(-1);
  };
  const stepOnce = () => {
    setPlaying(false);
    setCur((c) => Math.min(c + 1, steps.length - 1));
  };
  const toggle = () => {
    if (cur >= steps.length - 1) setCur(-1);
    setPlaying((p) => !p);
  };

  const laneIdx = Object.fromEntries(lanes.map((l, i) => [l.id, i]));
  const now = cur >= 0 && cur < steps.length ? steps[cur] : null;
  const ranLanes = new Set(steps.slice(0, cur + 1).map((s) => s.lane));

  return (
    <figure className="xt">
      <div className="xt-head">
        <span className="xt-title">{title ?? "Execution"}</span>
        <div className="xt-ctrls">
          <button
            className="xt-btn"
            onClick={() => setSpeed(SPEEDS[(SPEEDS.indexOf(speed as (typeof SPEEDS)[number]) + 1) % SPEEDS.length])}
            aria-label="Playback speed"
            title="Playback speed"
          >
            {speedLabel(speed)}
          </button>
          <button className="xt-btn" onClick={reset} aria-label="Reset">
            ⤺
          </button>
          <button className="xt-btn" onClick={stepOnce} aria-label="Step forward">
            ⏭
          </button>
          <button className="xt-btn xt-play" onClick={toggle}>
            {playing ? "❚❚ Pause" : "▶ Play"}
          </button>
        </div>
      </div>

      <div ref={matrixRef} className="xt-stage">
        {lanes.map((l) => {
          /* this lane's history: indexes of steps already played */
          const played = steps
            .map((s, i) => ({ s, i }))
            .filter(({ s, i }) => s.lane === l.id && i <= cur);
          const active = played.length > 0 && played[played.length - 1].i === cur;
          const pills = active ? played.slice(0, -1) : played;
          const current = active ? played[played.length - 1] : null;
          /* finished = its last authored step was `done` and has played:
             the gopher has left the building */
          const allLane = steps.filter((s) => s.lane === l.id);
          const lastKind = allLane[allLane.length - 1]?.kind ?? "run";
          const finished =
            played.length === allLane.length &&
            allLane.length > 0 &&
            lastKind === "done" &&
            now?.lane !== l.id;
          const gp = lanePose(now, l.id, ranLanes.has(l.id), finished);
          return (
            <div key={l.id} className={`xt-lane ${now?.lane === l.id ? "xt-lane-now" : ""}`}>
              <div className="xt-actor">
                <Gopher
                  pose={gp.pose}
                  state={gp.state}
                  size={34}
                  title={l.label}
                  tag={l.label.match(/(\d+)\s*$/)?.[1]}
                  role={
                    (now?.lane === l.id ? now.role : undefined) ??
                    l.role ??
                    inferRole(l.label)
                  }
                />
                <span className="xt-actor-name">{l.label}</span>
              </div>
              <div className="xt-track" data-track={l.id}>
                {pills.map(({ s, i }) => (
                  <span
                    key={i}
                    className={`xt-pill xt-${s.kind ?? "run"}`}
                    title={s.label}
                  >
                    {KIND_GLYPH[s.kind ?? "run"] ?? "▸"}
                  </span>
                ))}
                {current && (
                  <span
                    key={current.i}
                    data-i={current.i}
                    className={`xt-card xt-${current.s.kind ?? "run"}`}
                  >
                    <span className="xt-card-k">
                      {KIND_LABEL[current.s.kind ?? "run"] ?? current.s.kind}
                    </span>
                    <span className="xt-card-l">{current.s.label}</span>
                  </span>
                )}
              </div>
            </div>
          );
        })}
        {flight && (
          <span
            key={flight.key}
            className={`xt-token ${flying ? "xt-token-fly" : ""}`}
            style={
              {
                "--x0": `${flight.x0}px`,
                "--y0": `${flight.y0}px`,
                "--x1": `${flight.x1}px`,
                "--y1": `${flight.y1}px`,
              } as CSSProperties
            }
            aria-hidden
          />
        )}
      </div>

      <div className="xt-now">
        {now ? (
          <>
            <span className="xt-now-lane">
              {lanes[laneIdx[now.lane]]?.label}
            </span>
            <span className="xt-now-note">{now.note ?? now.label}</span>
          </>
        ) : (
          <span className="xt-now-idle">Press ▶ to watch it run, step by step.</span>
        )}
      </div>

      <div className="xt-progress">
        {steps.map((_, i) => (
          <button
            key={i}
            className={`xt-dot ${i === cur ? "on" : ""} ${i < cur ? "past" : ""}`}
            onClick={() => {
              setPlaying(false);
              setCur(i);
            }}
            aria-label={`Step ${i + 1}`}
          />
        ))}
      </div>

      {caption && <figcaption className="xt-cap">{caption}</figcaption>}
    </figure>
  );
}

type SceneState = "idle" | "active" | "ok" | "warn" | "bad" | "done";
type SceneActor = {
  id: string;
  label: string;
  state?: SceneState;
  at?: string;
  role?: GopherRole;
  /** explicit verb for this actor (overrides the state→pose mapping):
   *  "exit" walks out through a door, "enter" walks in, "carry", "sleep", … */
  pose?: GopherPose;
  /** chest badge; defaults to a trailing number in the label ("worker 3" → 3) */
  tag?: string;
};
type SceneCell = { id: string; label?: string; state?: SceneState };
type SceneFrame = {
  caption: string;
  beat?: "problem" | "solution" | "neutral";
  actors?: SceneActor[]; // overrides actor state this frame (by id)
  cells?: SceneCell[]; // overrides cell state this frame (by id)
};

/** Real-world SCENARIO illustration — the pictorial counterpart to ExecTimeline.
 *  Where ExecTimeline animates CODE execution, Scene animates the PROBLEM DOMAIN:
 *  a cinema seat grid, account balances, a request reaching a server. It plays a
 *  sequence of frames, each a problem/solution beat with a caption, recolouring a
 *  grid of cells and/or a row of labelled actors. Pure CSS/SVG, no deps. */
export function Scene({
  title,
  actors = [],
  rows,
  cols,
  cells: baseCells = [],
  frames,
  caption,
}: {
  title?: string;
  actors?: SceneActor[]; // the cast (users, services) shown as a row of pills
  rows?: number;
  cols?: number;
  cells?: SceneCell[]; // base grid cells (id like "A3"); states overridden per frame
  frames: SceneFrame[];
  caption?: string;
}) {
  const [cur, setCur] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [speed, setSpeed] = useState(1);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setCur((c) => {
        if (c >= frames.length - 1) {
          setPlaying(false);
          return c;
        }
        return c + 1;
      });
    }, 1600 / speed);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, frames.length, speed]);

  const frame = frames[cur] ?? frames[0];
  const prev = cur > 0 ? frames[cur - 1] : null;
  const beat = frame.beat ?? "neutral";

  // resolve per-frame overrides on top of base definitions
  const actorState = (a: SceneActor): SceneState => {
    const o = frame.actors?.find((x) => x.id === a.id);
    return o?.state ?? a.state ?? "idle";
  };
  const actorLabel = (a: SceneActor): string =>
    frame.actors?.find((x) => x.id === a.id)?.label ?? a.label;
  /* Per-frame role override = the MORPH: a frame can re-dress an actor as the
     character the beat is teaching (follower → "leader" when elected, service
     → "detective" when it starts tracing). Falls back to the actor's base
     role, then to inference from its label. */
  const actorRole = (a: SceneActor): GopherRole | undefined =>
    frame.actors?.find((x) => x.id === a.id)?.role ??
    a.role ??
    inferRole(actorLabel(a));
  /* Per-frame pose override = the VERB: "worker 3 exits" is authored as
     { id: "w3", pose: "exit" } and the gopher walks out through a door. */
  const actorPose = (a: SceneActor, st: SceneState): GopherPose =>
    frame.actors?.find((x) => x.id === a.id)?.pose ?? a.pose ?? ACTOR_POSE[st];
  /* identity badge: explicit tag, else the trailing number in the label */
  const actorTag = (a: SceneActor): string | undefined =>
    frame.actors?.find((x) => x.id === a.id)?.tag ??
    a.tag ??
    actorLabel(a).match(/(\d+)\s*$/)?.[1];
  const prevActorPose = (id: string): GopherPose | undefined =>
    prev?.actors?.find((x) => x.id === id)?.pose;

  // a cell/actor whose state OR costume changed this frame gets a pop
  const prevCellState = (id: string): SceneState | undefined =>
    prev?.cells?.find((c) => c.id === id)?.state;
  const prevActorState = (id: string): SceneState | undefined =>
    prev?.actors?.find((x) => x.id === id)?.state;
  const prevActorRole = (id: string): GopherRole | undefined =>
    prev?.actors?.find((x) => x.id === id)?.role;

  const ACTOR_POSE: Record<SceneState, GopherPose> = {
    idle: "idle",
    active: "run",
    ok: "happy",
    warn: "blocked",
    bad: "panic",
    done: "happy",
  };

  const gridCells: SceneCell[] =
    rows && cols
      ? Array.from({ length: rows * cols }, (_, i) => {
          const r = String.fromCharCode(65 + Math.floor(i / cols));
          const id = `${r}${(i % cols) + 1}`;
          const base = baseCells.find((c) => c.id === id);
          return { id, label: base?.label ?? id, state: base?.state };
        })
      : baseCells;

  const cellState = (id: string, fallback?: SceneState): SceneState =>
    frame.cells?.find((c) => c.id === id)?.state ?? fallback ?? "idle";
  const cellLabel = (c: SceneCell): string =>
    frame.cells?.find((x) => x.id === c.id)?.label ?? c.label ?? c.id;

  const toggle = () => {
    if (cur >= frames.length - 1) setCur(0);
    setPlaying((p) => !p);
  };

  return (
    <figure className="scn">
      <div className="scn-head">
        <span className="scn-title">{title ?? "Scenario"}</span>
        <div className="scn-ctrls">
          <button
            className="scn-btn"
            onClick={() => setSpeed(SPEEDS[(SPEEDS.indexOf(speed as (typeof SPEEDS)[number]) + 1) % SPEEDS.length])}
            aria-label="Playback speed"
            title="Playback speed"
          >
            {speedLabel(speed)}
          </button>
          <button className="scn-btn" onClick={() => { setPlaying(false); setCur(0); }} aria-label="Reset">⤺</button>
          <button className="scn-btn" onClick={() => { setPlaying(false); setCur((c) => Math.min(c + 1, frames.length - 1)); }} aria-label="Step">⏭</button>
          <button className="scn-btn scn-play" onClick={toggle}>{playing ? "❚❚ Pause" : "▶ Play"}</button>
        </div>
      </div>

      <div className="scn-stage">
        {actors.length > 0 && (
          <div className="scn-actors">
            {actors.map((a) => {
              const st = actorState(a);
              const role = actorRole(a);
              const pose = actorPose(a, st);
              const stateChanged =
                prevActorState(a.id) !== undefined && prevActorState(a.id) !== st;
              const morphed =
                prevActorRole(a.id) !== undefined && prevActorRole(a.id) !== role;
              const verbChanged =
                prevActorPose(a.id) !== undefined && prevActorPose(a.id) !== pose;
              const changed = stateChanged || morphed || verbChanged;
              const gone = pose === "exit";
              return (
                <span
                  key={changed ? `${a.id}@${cur}` : a.id}
                  className={`scn-actor-wrap ${changed && !gone ? "scn-pop" : ""} ${
                    gone ? "scn-gone" : ""
                  }`}
                >
                  <Gopher
                    pose={pose}
                    state={st}
                    size={46}
                    title={actorLabel(a)}
                    role={role}
                    tag={actorTag(a)}
                  />
                  <span className={`scn-actor scn-${st}`}>{actorLabel(a)}</span>
                </span>
              );
            })}
          </div>
        )}

        {gridCells.length > 0 && (
          <div
            className="scn-grid"
            style={{ ["--scols" as string]: String(cols ?? Math.ceil(Math.sqrt(gridCells.length))) } as CSSProperties}
          >
            {gridCells.map((c) => {
              const st = cellState(c.id, c.state);
              const before = prevCellState(c.id);
              const changed = before !== undefined && before !== st;
              return (
                <span
                  key={changed ? `${c.id}@${cur}` : c.id}
                  className={`scn-cell scn-${st} ${changed ? "scn-pop" : ""}`}
                  title={c.id}
                >
                  {cellLabel(c)}
                </span>
              );
            })}
          </div>
        )}
      </div>

      <div className={`scn-caption scn-beat-${beat}`}>
        <span className="scn-frameno">{cur + 1}/{frames.length}</span>
        {frame.caption}
      </div>

      <div className="scn-track">
        {frames.map((_, i) => (
          <button key={i} className={`scn-dot ${i === cur ? "on" : ""} ${i < cur ? "past" : ""}`} onClick={() => { setPlaying(false); setCur(i); }} aria-label={`Frame ${i + 1}`} />
        ))}
      </div>

      {caption && <figcaption className="scn-cap">{caption}</figcaption>}
    </figure>
  );
}

/** Inline single-answer knowledge check with instant feedback and retry support. */
export function QuickCheck({
  question,
  options,
  answer,
  explain,
}: {
  question: string;
  options: string[];
  answer: number;
  explain?: string;
}) {
  const [picked, setPicked] = useState<number | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const done = picked !== null;
  const isCorrect = picked === answer;

  const handlePick = (i: number) => {
    if (done && isCorrect) return;
    setPicked(i);
    if (i === answer) {
      recordQuickCheck(question);
      playSuccess();
      triggerConfetti();
    } else {
      playBuzzer();
    }
  };

  const handleReset = () => {
    setPicked(null);
    setShowExplanation(false);
    playClick();
  };

  return (
    <div className="qc">
      <div className="qc-q">
        <span className="qc-tag">Quick check</span>
        {question}
      </div>
      <div className="qc-opts">
        {options.map((o, i) => {
          const state = !done
            ? ""
            : i === answer
            ? "ok"
            : i === picked
            ? "no"
            : "dim";
          return (
            <button
              key={i}
              className={`qc-opt ${state}`}
              disabled={done && isCorrect}
              onClick={() => handlePick(i)}
              type="button"
            >
              <span className="qc-mark">
                {done && i === answer
                  ? "✓"
                  : done && i === picked
                  ? "✗"
                  : String.fromCharCode(65 + i)}
              </span>
              {o}
            </button>
          );
        })}
      </div>
      {done && (
        <div className={`qc-fb ${isCorrect ? "qc-ok" : "qc-no"}`}>
          <span className="qc-gopher" aria-hidden>
            <Gopher
              pose={isCorrect ? "happy" : "blocked"}
              state={isCorrect ? "ok" : "warn"}
              size={40}
              role="scientist"
              title={isCorrect ? "correct" : "not quite"}
            />
          </span>
          <div className="qc-fb-body">
            <span className="qc-fb-text">
              <strong>{isCorrect ? "Correct." : "Not quite."}</strong>{" "}
              {explain && (isCorrect || showExplanation) ? explain : null}
            </span>
            <div className="qc-fb-actions">
              {!isCorrect && (
                <>
                  <button className="qc-retry-btn" onClick={handleReset} type="button">
                    Try again
                  </button>
                  {!showExplanation && explain && (
                    <button
                      className="qc-explain-btn"
                      onClick={() => setShowExplanation(true)}
                      type="button"
                    >
                      Show explanation
                    </button>
                  )}
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

type Archetype =
  | "fix-it"
  | "find-it"
  | "build-it"
  | "optimize-it"
  | "break-fix"
  | "load";

const ARCH_LABEL: Record<Archetype, string> = {
  "fix-it": "Fix it",
  "find-it": "Find it",
  "build-it": "Build it",
  "optimize-it": "Optimize it",
  "break-fix": "Break, then fix",
  load: "Correct under load",
};

type VerifyTier = "verifier" | "self-check" | "reference";
const VERIFY_LABEL: Record<VerifyTier, string> = {
  verifier: "verifier-gated",
  "self-check": "self-check",
  reference: "reference",
};
const VERIFY_TIP: Record<VerifyTier, string> = {
  verifier: "The runner executes a real test/race/benchmark that gates the flag.",
  "self-check": "The lab code prints PASS/FAIL — correctness is visible without a hidden test.",
  reference: "Compare your solution against the provided reference and rubric (honor system).",
};

/** End-of-chapter capture-the-flag lab with live validation, reset, and flag copying. */
export function Lab({
  title,
  archetype = "build-it",
  difficulty = "guided",
  points = 50,
  hintCost = 10,
  objective,
  starter,
  hints = [],
  verifier,
  verify,
  expect,
  flag,
  children,
  onCapture,
}: {
  title: string;
  archetype?: Archetype;
  difficulty?: "guided" | "unscaffolded";
  points?: number;
  hintCost?: number;
  objective?: string;
  starter?: string;
  hints?: string[];
  verifier?: string;
  verify?: VerifyTier;
  expect?: string; // substring stdout must contain on a clean run to unlock the flag
  flag: string;
  children?: ReactNode;
  onCapture?: (flag: string, hintsUsed: number) => void;
}) {
  const [revealed, setRevealed] = useState(0);
  const [captured, setCaptured] = useState(false);
  const [copiedFlag, setCopiedFlag] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const [gofmtToast, setGofmtToast] = useState(false);
  const [ran, setRan] = useState(false);
  const snippetRef = useRef<HTMLElement | null>(null);
  const codeId = "lab-" + useId().replace(/[^a-zA-Z0-9_-]/g, "");

  // Watch real Codapi runs. Auto-unlock only on a clean build whose output
  // contains `expect`; otherwise just record that a run happened.
  useEffect(() => {
    const host = snippetRef.current;
    if (!host) return;
    const onResult = (e: Event) => {
      const d = (e as CustomEvent).detail as
        | { ok?: boolean; stdout?: string }
        | undefined;
      setRan(true);
      if (captured) return;
      if (!expect || (d?.ok && (d.stdout ?? "").includes(expect))) {
        setCaptured(true);
        recordLab(title, flag);
        playFlag();
        triggerConfetti();
        onCapture?.(flag, revealed);
      }
    };
    host.addEventListener("result", onResult as EventListener);
    return () => host.removeEventListener("result", onResult as EventListener);
  }, [captured, expect, flag, revealed, onCapture, title]);

  const revealManually = () => {
    setCaptured(true);
    recordLab(title, flag);
    playFlag();
    triggerConfetti();
    onCapture?.(flag, revealed);
  };

  const copyFlagToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(flag);
      setCopiedFlag(true);
      setTimeout(() => setCopiedFlag(false), 2000);
    } catch {
      /* clipboard blocked */
    }
  };

  const resetStarter = () => {
    if (!starter) return;
    const el = document.getElementById(codeId);
    if (el) {
      const codeEl = el.querySelector("code") || el;
      codeEl.innerHTML = highlightGo(starter.replace(/^\n+|\n+$/g, ""));
    }
    playClick();
  };

  const handleGofmt = () => {
    const el = document.getElementById(codeId);
    if (!el) return;
    const text = el.textContent ?? "";
    const { formatted } = formatGo(text);
    const codeEl = el.querySelector("code") || el;
    codeEl.innerHTML = highlightGo(formatted);
    playClick();
    setGofmtToast(true);
    setTimeout(() => setGofmtToast(false), 1400);
  };

  return (
    <section className="lab">
      <div className="lab-head">
        <span className="lab-kicker">Lab — Capture the Flag</span>
        <div className="lab-tags">
          <span className="lab-tag">{ARCH_LABEL[archetype]}</span>
          {verify && (
            <span className={`lab-tag lab-verify lab-verify-${verify}`} title={VERIFY_TIP[verify]}>
              {VERIFY_LABEL[verify]}
            </span>
          )}
          <span className={`lab-tag lab-diff-${difficulty}`}>{difficulty}</span>
          <span className="lab-tag lab-pts">{points} pts</span>
        </div>
      </div>
      <h3 className="lab-title">{title}</h3>
      {objective && (
        <p className="lab-objective">
          <strong>Objective.</strong> {objective}
        </p>
      )}
      {children && <div className="lab-brief">{children}</div>}

      {starter && (
        <div className="lab-starter gb-ide-window" style={{ position: "relative" }}>
          {gofmtToast && (
            <div className="gb-gofmt-toast">
              ⚡ gofmt applied
            </div>
          )}
          <div className="lab-starter-bar gb-ide-bar">
            <div className="gb-ide-left">
              <span className="gb-ide-dots">
                <i className="gb-dot-r" />
                <i className="gb-dot-y" />
                <i className="gb-dot-g" />
              </span>
              <div className="gb-ide-tab">
                <span className="gb-ide-folder">📁 lab / </span>
                <span className="gb-ide-file">📄 starter.go</span>
              </div>
            </div>
            <div className="gb-ide-right">
              <button
                className="lab-reset-btn"
                onClick={resetStarter}
                type="button"
                title="Reset starter code"
              >
                ↺ Reset
              </button>
              <button
                className="lab-reset-btn"
                onClick={handleGofmt}
                type="button"
                title="Format with gofmt (⌘S / Ctrl+S)"
              >
                ⚡ Format
              </button>
              <button
                className="gb-ide-copy"
                onClick={async () => {
                  const el = document.getElementById(codeId);
                  if (el) {
                    await navigator.clipboard.writeText(el.textContent ?? "");
                    setCopiedCode(true);
                    setTimeout(() => setCopiedCode(false), 1400);
                  }
                }}
                type="button"
                aria-label="Copy code"
              >
                {copiedCode ? "Copied ✓" : "Copy"}
              </button>
              <span className="gb-ide-lang">GO 1.26</span>
              <span className="ply-hint">runnable</span>
            </div>
          </div>
          <pre className="lab-code" id={codeId} spellCheck={false}>
            <code dangerouslySetInnerHTML={{ __html: highlightGo(starter.replace(/^\n+|\n+$/g, "")) }} />
          </pre>
          <div className="lab-snippet">
            {createElement("codapi-snippet", {
              ref: snippetRef,
              sandbox: "go",
              editor: "basic",
              selector: `#${codeId}`,
            })}
          </div>
        </div>
      )}

      {verifier && (
        <p className="lab-verifier">
          <span className="lab-verifier-tag">verifier</span>
          {verifier}
        </p>
      )}

      {hints.length > 0 && (
        <div className="lab-hints">
          {hints.map((h, i) =>
            i < revealed ? (
              <p key={i} className="lab-hint-text">
                <span className="lab-hint-n">Hint {i + 1}</span>
                {h}
              </p>
            ) : i === revealed ? (
              <button
                key={i}
                className="lab-hint-btn"
                onClick={() => setRevealed((r) => r + 1)}
                type="button"
              >
                Reveal hint {i + 1}
                <span className="lab-hint-cost">−{hintCost} pts</span>
              </button>
            ) : null
          )}
        </div>
      )}

      <div className="lab-run">
        {captured ? (
          <span className="lab-run-state">Flag unlocked</span>
        ) : (
          <div className="lab-actions-row">
            <button className="lab-run-btn" onClick={revealManually} type="button">
              {expect && starter ? "Verify & Unlock Flag" : "Reveal Flag"}
            </button>
            {expect && starter && (
              <span className="lab-run-note">
                {ran
                  ? "Output not matching yet — fix the code or click Verify & Unlock."
                  : "Edit the code and click Run above, or click Verify & Unlock."}
              </span>
            )}
          </div>
        )}
        {revealed > 0 && !captured && (
          <span className="lab-run-note">{revealed} hint(s) used</span>
        )}
      </div>

      {captured && (
        <div className="lab-flag">
          <div className="lab-flag-header">
            <span className="lab-flag-label">Flag captured</span>
            <button
              className="lab-flag-copy"
              onClick={copyFlagToClipboard}
              type="button"
            >
              {copiedFlag ? "Copied" : "Copy Flag"}
            </button>
          </div>
          <code className="lab-flag-code">{flag}</code>
          <p className="lab-flag-note">
            {expect && starter
              ? "Verified — your code built clean and satisfied the verification criteria."
              : "Completed on the honor system. Check your solution against the objective and hints above."}
          </p>
        </div>
      )}
    </section>
  );
}

type ScoreItem = {
  label: string;
  kind?: "quiz" | "exercise" | "lab";
  points?: number;
  done?: boolean;
};

/** End-of-chapter progress panel. */
export function Scoreboard({
  points,
  total,
  streak,
  items = [],
  flag,
}: {
  points?: number;
  total?: number;
  streak?: number;
  items?: ScoreItem[];
  flag?: { label: string; captured?: boolean; points?: number };
}) {
  const all: ScoreItem[] = [
    ...items,
    ...(flag
      ? [
          {
            label: flag.label,
            kind: "lab" as const,
            points: flag.points ?? 50,
            done: flag.captured,
          },
        ]
      : []),
  ];
  const computedTotal =
    total ?? all.reduce((s, i) => s + (i.points ?? 10), 0);
  const computedPoints =
    points ?? all.reduce((s, i) => s + (i.done ? i.points ?? 10 : 0), 0);
  const pct = computedTotal
    ? Math.round((computedPoints / computedTotal) * 100)
    : 0;

  const [w, setW] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setW(pct), 120);
    return () => clearTimeout(t);
  }, [pct]);

  return (
    <section className="sb">
      <div className="sb-head">
        <span className="sb-kicker">Scoreboard</span>
        {typeof streak === "number" && (
          <span className="sb-streak">{streak} day streak</span>
        )}
      </div>
      <div className="sb-score">
        <span className="sb-pts">{computedPoints}</span>
        <span className="sb-of">/ {computedTotal} pts</span>
        <span className="sb-pct">{pct}%</span>
      </div>
      <div className="sb-track">
        <div className="sb-fill" style={{ width: `${w}%` }} />
      </div>
      <ul className="sb-items">
        {all.map((it, i) => (
          <li
            key={i}
            className={`sb-item ${it.done ? "done" : ""} ${
              it.kind === "lab" ? "sb-lab" : ""
            }`}
          >
            <span className="sb-check">{it.done ? "✓" : "○"}</span>
            <span className="sb-label">{it.label}</span>
            <span className="sb-ip">{it.points ?? 10}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

