"use client";

import {
  Fragment,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { slug as ghSlug } from "github-slugger";

/* ──────────────────────────────────────────────
   Interactive (client) course components.
   Animations are CSS/JS only — no animation libs,
   honoring the prompt's "no deps beyond React".
   ────────────────────────────────────────────── */

/** Numbered sub-topic tab strip with a scroll-synced progress bar.
 *  `tabs` labels must match the H2 headings in the chapter; ids are
 *  generated by rehype-slug and matched here with github-slugger. */
export function ChapterTabs({ tabs }: { tabs: string[] }) {
  const [active, setActive] = useState(0);

  useEffect(() => {
    const ids = tabs.map((t) => ghSlug(t));
    const els = ids
      .map((id) => document.getElementById(id))
      .filter(Boolean) as HTMLElement[];
    if (!els.length) return;
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            const i = ids.indexOf((e.target as HTMLElement).id);
            if (i >= 0) setActive(i);
          }
        });
      },
      { rootMargin: "-45% 0px -50% 0px", threshold: 0 }
    );
    els.forEach((el) => obs.observe(el));
    return () => obs.disconnect();
  }, [tabs]);

  const go = (i: number) => {
    const el = document.getElementById(ghSlug(tabs[i]));
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
    setActive(i);
  };

  return (
    <nav className="tabs" aria-label="Chapter sections">
      <div className="tabs-row">
        {tabs.map((t, i) => (
          <button
            key={t}
            className={`tab ${i === active ? "tab-active" : ""} ${
              i < active ? "tab-done" : ""
            }`}
            onClick={() => go(i)}
          >
            <span className="tab-n">{i + 1}</span>
            <span className="tab-label">{t}</span>
          </button>
        ))}
      </div>
      <div className="tabs-track">
        <div
          className="tabs-fill"
          style={{ width: `${((active + 1) / tabs.length) * 100}%` }}
        />
      </div>
    </nav>
  );
}

type Lane = { id: string; label: string };
type StepKind = "run" | "block" | "send" | "recv" | "spawn" | "done";
type Step = {
  lane: string;
  label: string;
  note?: string;
  kind?: StepKind;
};

const KIND_LABEL: Record<StepKind, string> = {
  run: "run",
  block: "block",
  send: "send ►",
  recv: "◄ recv",
  spawn: "go ✦",
  done: "done ✓",
};

/** Stepped "play" timeline. Lanes on the Y axis (e.g. goroutines / main),
 *  global ticks on the X axis. Reveals one step per tick so you watch the
 *  mechanism unfold — sequential on one lane, concurrent across many. */
export function ExecTimeline({
  title,
  lanes,
  steps,
  caption,
}: {
  title?: string;
  lanes: Lane[];
  steps: Step[];
  caption?: string;
}) {
  const [cur, setCur] = useState(-1);
  const [playing, setPlaying] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setCur((c) => {
        if (c >= steps.length - 1) {
          setPlaying(false);
          return c;
        }
        return c + 1;
      });
    }, 820);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, steps.length]);

  const reset = () => {
    setPlaying(false);
    setCur(-1);
  };
  const stepOnce = () => {
    setPlaying(false);
    setCur((c) => Math.min(c + 1, steps.length - 1));
  };
  const toggle = () => {
    if (cur >= steps.length - 1) setCur(-1);
    setPlaying((p) => !p);
  };

  const laneIdx = Object.fromEntries(lanes.map((l, i) => [l.id, i]));
  const now = cur >= 0 && cur < steps.length ? steps[cur] : null;

  return (
    <figure className="xt">
      <div className="xt-head">
        <span className="xt-title">{title ?? "Execution"}</span>
        <div className="xt-ctrls">
          <button className="xt-btn" onClick={reset} aria-label="Reset">
            ⤺
          </button>
          <button className="xt-btn" onClick={stepOnce} aria-label="Step forward">
            ⏭
          </button>
          <button className="xt-btn xt-play" onClick={toggle}>
            {playing ? "❚❚ Pause" : "▶ Play"}
          </button>
        </div>
      </div>

      <div className="xt-scroll">
        <div
          className="xt-matrix"
          style={{ "--ticks": String(steps.length) } as CSSProperties}
        >
          {lanes.map((l, li) => (
            <Fragment key={l.id}>
              <div
                className="xt-row-label"
                style={{ gridRow: li + 1, gridColumn: 1 }}
              >
                {l.label}
              </div>
              {steps.map((s, i) =>
                s.lane === l.id ? (
                  <div
                    key={i}
                    className={`xt-cell xt-${s.kind ?? "run"} ${
                      i <= cur ? "on" : ""
                    } ${i === cur ? "now" : ""}`}
                    style={{ gridRow: li + 1, gridColumn: i + 2 }}
                  >
                    <span className="xt-cell-k">
                      {KIND_LABEL[s.kind ?? "run"]}
                    </span>
                    <span className="xt-cell-l">{s.label}</span>
                  </div>
                ) : null
              )}
            </Fragment>
          ))}
        </div>
      </div>

      <div className="xt-now">
        {now ? (
          <>
            <span className="xt-now-lane">
              {lanes[laneIdx[now.lane]]?.label}
            </span>
            {now.note ?? now.label}
          </>
        ) : (
          <span className="xt-now-idle">Press ▶ to watch it run, step by step.</span>
        )}
      </div>

      {caption && <figcaption className="xt-cap">{caption}</figcaption>}
    </figure>
  );
}

type SceneState = "idle" | "active" | "ok" | "warn" | "bad" | "done";
type SceneActor = { id: string; label: string; state?: SceneState; at?: string };
type SceneCell = { id: string; label?: string; state?: SceneState };
type SceneFrame = {
  caption: string;
  beat?: "problem" | "solution" | "neutral";
  actors?: SceneActor[]; // overrides actor state this frame (by id)
  cells?: SceneCell[]; // overrides cell state this frame (by id)
};

/** Real-world SCENARIO illustration — the pictorial counterpart to ExecTimeline.
 *  Where ExecTimeline animates CODE execution, Scene animates the PROBLEM DOMAIN:
 *  a cinema seat grid, account balances, a request reaching a server. It plays a
 *  sequence of frames, each a problem/solution beat with a caption, recolouring a
 *  grid of cells and/or a row of labelled actors. Pure CSS/SVG, no deps. */
export function Scene({
  title,
  actors = [],
  rows,
  cols,
  cells: baseCells = [],
  frames,
  caption,
}: {
  title?: string;
  actors?: SceneActor[]; // the cast (users, services) shown as a row of pills
  rows?: number;
  cols?: number;
  cells?: SceneCell[]; // base grid cells (id like "A3"); states overridden per frame
  frames: SceneFrame[];
  caption?: string;
}) {
  const [cur, setCur] = useState(0);
  const [playing, setPlaying] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setCur((c) => {
        if (c >= frames.length - 1) {
          setPlaying(false);
          return c;
        }
        return c + 1;
      });
    }, 1600);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, frames.length]);

  const frame = frames[cur] ?? frames[0];
  const beat = frame.beat ?? "neutral";

  // resolve per-frame overrides on top of base definitions
  const actorState = (a: SceneActor): SceneState => {
    const o = frame.actors?.find((x) => x.id === a.id);
    return o?.state ?? a.state ?? "idle";
  };
  const actorLabel = (a: SceneActor): string =>
    frame.actors?.find((x) => x.id === a.id)?.label ?? a.label;

  const gridCells: SceneCell[] =
    rows && cols
      ? Array.from({ length: rows * cols }, (_, i) => {
          const r = String.fromCharCode(65 + Math.floor(i / cols));
          const id = `${r}${(i % cols) + 1}`;
          const base = baseCells.find((c) => c.id === id);
          return { id, label: base?.label ?? id, state: base?.state };
        })
      : baseCells;

  const cellState = (id: string, fallback?: SceneState): SceneState =>
    frame.cells?.find((c) => c.id === id)?.state ?? fallback ?? "idle";
  const cellLabel = (c: SceneCell): string =>
    frame.cells?.find((x) => x.id === c.id)?.label ?? c.label ?? c.id;

  const toggle = () => {
    if (cur >= frames.length - 1) setCur(0);
    setPlaying((p) => !p);
  };

  return (
    <figure className="scn">
      <div className="scn-head">
        <span className="scn-title">{title ?? "Scenario"}</span>
        <div className="scn-ctrls">
          <button className="scn-btn" onClick={() => { setPlaying(false); setCur(0); }} aria-label="Reset">⤺</button>
          <button className="scn-btn" onClick={() => { setPlaying(false); setCur((c) => Math.min(c + 1, frames.length - 1)); }} aria-label="Step">⏭</button>
          <button className="scn-btn scn-play" onClick={toggle}>{playing ? "❚❚ Pause" : "▶ Play"}</button>
        </div>
      </div>

      <div className="scn-stage">
        {actors.length > 0 && (
          <div className="scn-actors">
            {actors.map((a) => (
              <span key={a.id} className={`scn-actor scn-${actorState(a)}`}>
                {actorLabel(a)}
              </span>
            ))}
          </div>
        )}

        {gridCells.length > 0 && (
          <div
            className="scn-grid"
            style={{ ["--scols" as string]: String(cols ?? Math.ceil(Math.sqrt(gridCells.length))) } as CSSProperties}
          >
            {gridCells.map((c) => {
              const st = cellState(c.id, c.state);
              return (
                <span key={c.id} className={`scn-cell scn-${st}`} title={c.id}>
                  {cellLabel(c)}
                </span>
              );
            })}
          </div>
        )}
      </div>

      <div className={`scn-caption scn-beat-${beat}`}>
        <span className="scn-frameno">{cur + 1}/{frames.length}</span>
        {frame.caption}
      </div>

      <div className="scn-track">
        {frames.map((_, i) => (
          <button key={i} className={`scn-dot ${i === cur ? "on" : ""} ${i < cur ? "past" : ""}`} onClick={() => { setPlaying(false); setCur(i); }} aria-label={`Frame ${i + 1}`} />
        ))}
      </div>

      {caption && <figcaption className="scn-cap">{caption}</figcaption>}
    </figure>
  );
}

/** Inline single-answer knowledge check with instant feedback. */
export function QuickCheck({
  question,
  options,
  answer,
  explain,
}: {
  question: string;
  options: string[];
  answer: number;
  explain?: string;
}) {
  const [picked, setPicked] = useState<number | null>(null);
  const done = picked !== null;
  return (
    <div className="qc">
      <div className="qc-q">
        <span className="qc-tag">Quick check</span>
        {question}
      </div>
      <div className="qc-opts">
        {options.map((o, i) => {
          const state = !done
            ? ""
            : i === answer
            ? "ok"
            : i === picked
            ? "no"
            : "dim";
          return (
            <button
              key={i}
              className={`qc-opt ${state}`}
              disabled={done}
              onClick={() => setPicked(i)}
            >
              <span className="qc-mark">
                {done && i === answer
                  ? "✓"
                  : done && i === picked
                  ? "✗"
                  : String.fromCharCode(65 + i)}
              </span>
              {o}
            </button>
          );
        })}
      </div>
      {done && (
        <div className={`qc-fb ${picked === answer ? "qc-ok" : "qc-no"}`}>
          <strong>{picked === answer ? "Correct." : "Not quite."}</strong>{" "}
          {explain}
        </div>
      )}
    </div>
  );
}

type Archetype =
  | "fix-it"
  | "find-it"
  | "build-it"
  | "optimize-it"
  | "break-fix"
  | "load";

const ARCH_LABEL: Record<Archetype, string> = {
  "fix-it": "Fix it",
  "find-it": "Find it",
  "build-it": "Build it",
  "optimize-it": "Optimize it",
  "break-fix": "Break, then fix",
  load: "Correct under load",
};

type VerifyTier = "verifier" | "self-check" | "reference";
const VERIFY_LABEL: Record<VerifyTier, string> = {
  verifier: "✓ verifier-gated",
  "self-check": "self-check",
  reference: "reference",
};
const VERIFY_TIP: Record<VerifyTier, string> = {
  verifier: "The runner executes a real test/race/benchmark that gates the flag.",
  "self-check": "The lab's own code prints PASS/FAIL — correctness is visible without a hidden test.",
  reference: "Compare your solution against the provided reference and rubric (honor system).",
};

/** End-of-chapter capture-the-flag lab. Placeholder runner: the live site
 *  wires this to the Codapi/verifier harness. No storage — captures emit via
 *  the optional onCapture callback. */
export function Lab({
  title,
  archetype = "build-it",
  difficulty = "guided",
  points = 50,
  hintCost = 10,
  objective,
  starter,
  hints = [],
  verifier,
  verify,
  flag,
  children,
  onCapture,
}: {
  title: string;
  archetype?: Archetype;
  difficulty?: "guided" | "unscaffolded";
  points?: number;
  hintCost?: number;
  objective?: string;
  starter?: string;
  hints?: string[];
  verifier?: string;
  verify?: VerifyTier;
  flag: string;
  children?: ReactNode;
  onCapture?: (flag: string, hintsUsed: number) => void;
}) {
  const [revealed, setRevealed] = useState(0);
  const [captured, setCaptured] = useState(false);
  const [running, setRunning] = useState(false);

  const run = () => {
    setRunning(true);
    setTimeout(() => {
      setRunning(false);
      setCaptured(true);
      onCapture?.(flag, revealed);
    }, 900);
  };

  return (
    <section className="lab">
      <div className="lab-head">
        <span className="lab-kicker">⚑ Lab — capture the flag</span>
        <div className="lab-tags">
          <span className="lab-tag">{ARCH_LABEL[archetype]}</span>
          {verify && (
            <span className={`lab-tag lab-verify lab-verify-${verify}`} title={VERIFY_TIP[verify]}>
              {VERIFY_LABEL[verify]}
            </span>
          )}
          <span className={`lab-tag lab-diff-${difficulty}`}>{difficulty}</span>
          <span className="lab-tag lab-pts">{points} pts</span>
        </div>
      </div>
      <h3 className="lab-title">{title}</h3>
      {objective && (
        <p className="lab-objective">
          <strong>Objective.</strong> {objective}
        </p>
      )}
      {children && <div className="lab-brief">{children}</div>}

      {starter && (
        <div className="lab-starter">
          <div className="lab-starter-bar">
            <span>starter.go</span>
            <span className="lab-starter-tag">sandbox</span>
          </div>
          <pre className="lab-code">
            <code>{starter.replace(/^\n+|\n+$/g, "")}</code>
          </pre>
        </div>
      )}

      {verifier && (
        <p className="lab-verifier">
          <span className="lab-verifier-tag">verifier</span>
          {verifier}
        </p>
      )}

      {hints.length > 0 && (
        <div className="lab-hints">
          {hints.map((h, i) =>
            i < revealed ? (
              <p key={i} className="lab-hint-text">
                <span className="lab-hint-n">Hint {i + 1}</span>
                {h}
              </p>
            ) : i === revealed ? (
              <button
                key={i}
                className="lab-hint-btn"
                onClick={() => setRevealed((r) => r + 1)}
              >
                Reveal hint {i + 1}
                <span className="lab-hint-cost">−{hintCost} pts</span>
              </button>
            ) : null
          )}
        </div>
      )}

      <div className="lab-run">
        <button
          className="lab-run-btn"
          onClick={run}
          disabled={running || captured}
        >
          {captured
            ? "✓ Verifier passed"
            : running
            ? "Running verifier…"
            : "▶ Run the verifier"}
        </button>
        {revealed > 0 && !captured && (
          <span className="lab-run-note">{revealed} hint(s) used</span>
        )}
      </div>

      {captured && (
        <div className="lab-flag">
          <span className="lab-flag-label">⚑ Flag captured</span>
          <code className="lab-flag-code">{flag}</code>
          <p className="lab-flag-note">
            Genuinely solved — the flag is derived from the verifier passing, not
            pasted in. (Placeholder runner; the site maps this to the real lab
            harness.)
          </p>
        </div>
      )}
    </section>
  );
}

type ScoreItem = {
  label: string;
  kind?: "quiz" | "exercise" | "lab";
  points?: number;
  done?: boolean;
};

/** End-of-chapter progress panel. Presentational: progress comes in via props,
 *  no storage — the site supplies real state and wires its own store. */
export function Scoreboard({
  points,
  total,
  streak,
  items = [],
  flag,
}: {
  points?: number;
  total?: number;
  streak?: number;
  items?: ScoreItem[];
  flag?: { label: string; captured?: boolean; points?: number };
}) {
  const all: ScoreItem[] = [
    ...items,
    ...(flag
      ? [
          {
            label: flag.label,
            kind: "lab" as const,
            points: flag.points ?? 50,
            done: flag.captured,
          },
        ]
      : []),
  ];
  const computedTotal =
    total ?? all.reduce((s, i) => s + (i.points ?? 10), 0);
  const computedPoints =
    points ?? all.reduce((s, i) => s + (i.done ? i.points ?? 10 : 0), 0);
  const pct = computedTotal
    ? Math.round((computedPoints / computedTotal) * 100)
    : 0;

  const [w, setW] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setW(pct), 120);
    return () => clearTimeout(t);
  }, [pct]);

  return (
    <section className="sb">
      <div className="sb-head">
        <span className="sb-kicker">Scoreboard</span>
        {typeof streak === "number" && (
          <span className="sb-streak">🔥 {streak} streak</span>
        )}
      </div>
      <div className="sb-score">
        <span className="sb-pts">{computedPoints}</span>
        <span className="sb-of">/ {computedTotal} pts</span>
        <span className="sb-pct">{pct}%</span>
      </div>
      <div className="sb-track">
        <div className="sb-fill" style={{ width: `${w}%` }} />
      </div>
      <ul className="sb-items">
        {all.map((it, i) => (
          <li
            key={i}
            className={`sb-item ${it.done ? "done" : ""} ${
              it.kind === "lab" ? "sb-lab" : ""
            }`}
          >
            <span className="sb-check">{it.done ? "✓" : "○"}</span>
            <span className="sb-label">{it.label}</span>
            <span className="sb-ip">{it.points ?? 10}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}
